name: PR Check

on:
  pull_request:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup ImageMagick
        run: sudo apt-get install imagemagick -y
      - name: Print file diffs in svg and png folders
        run: |
          changed_files=$(git diff --name-only origin/main -- ./svg ./png)
          for file in $changed_files
          do
            file_type=$(file --mime-type -b $file)
            if [[ $file == *.svg && $file_type != "image/svg+xml" ]]; then
              echo "::warning:: $file is not a valid $file_type file"
            elif [[ $file == *.png ]]; then
              if [[ $file_type != "image/png" ]]; then
                echo "::warning:: $file is not a valid $file_type file"
              fi
              image_size=$(identify -format "%wx%h" $file)
              if [[ $image_size != "512x512" ]]; then
                echo "::warning:: $file is not 512x512, it's $image_size"
              fi
            fi
          done    
        