name: PR Check

on:
  pull_request:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print file diffs in svg and png folders
        run: |
          git diff --name-only origin/main -- ./svg ./png
          
        