name: PR Check

on:
  pull_request:

jobs:
  pr-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get all changed png files
        id: changed-png-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
             png/*.png
      - name: List all changed files png files
        if: steps.changed-png-files.outputs.any_changed == 'true'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-png-files.outputs.all_changed_files }}
        run: |
          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"
            image_size=$(identify -format "%wx%h" $file)
            if [[ $image_size != "512x512" ]]; then
              echo "::warning:: $file is not 512x512, it's $image_size"
              # exit 1
            else
              echo "file is valid"
            fi
          done      
          